### PR TITLE
Support magic tap on iOS

### LINKED ISSUE #55: Support magic tap
See https://reactnative.dev/docs/accessibility#onmagictap-ios

### PR DESCRIPTION
**Pull request by simonwacker**
Closes #55 

Implement [`onMagicTap`](https://reactnative.dev/docs/accessibility#onmagictap-ios) for

- [x] Buttons
- [x] Checkboxes
- [x] Textfields on screens with one textfield and a single button
- [x] Slider component
- [x] React navigation back button
- [x] Screens with one primary button that is being pressed on magic tap

Implement [`onAccessibilityEscape`](https://reactnative.dev/docs/accessibility#onaccessibilityescape-ios) for

- [x] Screens (navigate back)
- [x] Audio player with multiple tracks (go to previous track if there is one)

Implement [accessibility actions](https://reactnative.dev/docs/accessibility#accessibility-actions) for

- [x] ~~Slider~~ This is not needed. Setting the role to `adjustable` is enough. Also according to https://github.com/simonwacker/yoga-insights/pull/61#issuecomment-960601775 and https://github.com/callstack/react-native-slider/issues/250 accessibility actions do not work for sliders.
- [x] Is there some other component where this could be useful? I couldn't think of one.

Should we implement [`onAccessibilityTap`](https://reactnative.dev/docs/accessibility#onaccessibilitytap) for some component? Opened issue #64 with that question. Let's keep this pull request small.

### CODE REVIEW

**Comment by simonwacker** [comment]
@timhabermaas Could you check whether magic tap works for the first three items on your phone?

**Comment by timhabermaas** [comment]
Unfortunately I get the following exception on iOS when opening the app (neither reloading, killing expo, reinstalling `node_modules` helped):

6310F7D0-0E57-415C-93ED-C526154DECDC

Before 5afff424aadaed6b6a89c8f06ebbb638b04d6e82 I got the same exception with `setOnAccessibilityAction` instead of `setOnMagicTap`.

It doesn't matter if VoiceOver is enabled or disabled. I get the exception either way.


I couldn't find posts/issues with this exception. People get similar exceptions when passing `null` into things which aren't supposed to accept `null`, but I don't see any possible `null` values here... 🤔

**Comment by timhabermaas** [comment]
Found the offending `onMagicTap` by some trial&error:

```diff
diff --git a/app/components/download-switch/download-switch.tsx b/app/components/download-switch/download-switch.tsx
index da04b28..a825f01 100644
--- a/app/components/download-switch/download-switch.tsx
+++ b/app/components/download-switch/download-switch.tsx
@@ -81,7 +81,6 @@ export function DownloadSwitch({ tracks }: DownloadSwitchProps) {
         disabled={downloadState.type === "UNKNOWN"}
         value={downloadState.type === "DOWNLOADING" || downloadState.type === "DOWNLOADED"}
         onValueChange={onSwitchValueChange}
-        onMagicTap={onSwitchValueChange}
       />
       {downloadState.type === "DOWNLOADING" && (
         <Text
```

Without this line there's no exception thrown anymore. Maybe `Switch` simply doesn't support magic tap and the react-native API isn't quite right?

For playing/pausing the two-finger double-tap works to start/pause the audio. Need to check the rest now.

**Comment by simonwacker** [comment]
> Maybe `Switch` simply doesn't support magic tap and the react-native API isn't quite right?

I removed `onMagicTap` for `Switch` in https://github.com/simonwacker/yoga-insights/pull/61/commits/c9b7eee97fc3e12ec1997bba0c848bbc5c8ec18b and opened issue #62

**Comment by simonwacker** [comment]
I didn't want this branch to hang around for too long. So I merged it. @timhabermaas If you still find time to test magic tap, please do so and open issues for things that don't work.

**Pull request merged**
